name: Run Tests

on:
  push:
    paths:
      - '.github/workflows/run-tests.yml'
      - 'src/**'
      - 'package.json'
      - 'shadow-cljs.edn'

jobs:
  checkout-and-install-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          persist-credentials: false    
      - name: NPM Install ğŸ’¾
        run: npm install

  run-cljs-tests:
    runs-on: ubuntu-latest
    needs: checkout-and-install-deps
    steps:
      - name: Run CLJS Tests ğŸ§¾ 
        run: npx shadow-cljs compile :test
