name: Run Tests

on:
  push:
    branches: [ benchmarks ]
  pull_request:
    branches: [ benchmarks]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
        with:
          ref: benchmarks
          persist-credentials: false

      - name: Install and Build ğŸ”§
        run: |
          npm install
          npx shadow-cljs compile ci


      - name: Test ğŸ§ª
        run: |
          cd src/test
          karma start
